#include "Stage1.h"
#include "Enemy.h"


namespace BestStealReplica {
namespace Stage {
namespace {

using Map::MapCommon;
using Character::CharacterCommon;
using Character::Enemy;

MapCommon::MapChipType mapChipTypes[Stage1::Y_CHIP_COUNT][Stage1::X_CHIP_COUNT] = {
	// 1									2									3									4									5									6									7									8									9									10									11									12									13									14									15									16									17									18									19									20									21									22									23									24									25									26									27									28									29									30
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD },		// 1
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD },		// 2
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD },		// 3
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD },		// 4
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD },		// 5
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD },		// 6
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD },		// 7
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL },		// 8
	{ MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::DOOR, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE },// 9
	{ MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD },		// 10
	{ MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::DOOR, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL },		// 11
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE },// 12
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::JEWELRY, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD },		// 13
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL },		// 14
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL },		// 15
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::GOLD_DOOR, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL },		// 16
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::DOOR, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::DOOR, MapCommon::MapChipType::WALL_SIDE },// 17
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD },		// 18
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD },		// 19
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD },		// 20
	{ MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::WALL_SIDE, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD, MapCommon::MapChipType::ROAD },		// 21
};

Enemy::EnemyInfo enemiesInfo[Stage1::ENEMY_COUNT] = {
	Enemy::EnemyInfo(6, 4, AppCommon::Direction::RIGHT, AppCommon::KeyType::None),
	Enemy::EnemyInfo(24, 0, AppCommon::Direction::LEFT, AppCommon::KeyType::Silver),
	Enemy::EnemyInfo(1, 20, AppCommon::Direction::RIGHT, AppCommon::KeyType::Silver),
	Enemy::EnemyInfo(22, 7, AppCommon::Direction::LEFT, AppCommon::KeyType::None),
	Enemy::EnemyInfo(3, 16, AppCommon::Direction::BOTTOM, AppCommon::KeyType::Silver),
	Enemy::EnemyInfo(9, 20, AppCommon::Direction::RIGHT, AppCommon::KeyType::Silver),
	Enemy::EnemyInfo(21, 14, AppCommon::Direction::RIGHT, AppCommon::KeyType::Gold)
};

}

/* Getters / Setters -------------------------------------------------------------------------------- */
int Stage1::GetYChipCount() const {
	return Stage1::Y_CHIP_COUNT;
}

int Stage1::GetXChipCount() const {
	return Stage1::X_CHIP_COUNT;
}

MapCommon::MapChipType Stage1::GetMapChipType(int y, int x) const {
	return mapChipTypes[y][x];
}

POINT Stage1::GetPlayerFirstChipPos() const {
	POINT ret;
	ret.x = 14;
	ret.y = 20;
	return ret;
}

int Stage1::GetEnemyCount() const {
	return Stage1::ENEMY_COUNT;
}

POINT Stage1::GetEnemyChipPos(int enemyNum) const {
	return enemiesInfo[enemyNum].chipPos;
}

Enemy::EnemyInfo* Stage1::GetEnemiesInfo() const {
	return enemiesInfo;
}

int Stage1::GetEnemyScoutableRadius() const {
	return 260;
}

int Stage1::GetMaxStoneCount() const {
	return MAX_STONE_COUNT;
}

}
}